package tn.esprit.examen.Smartmeet.entities.MaryemJeljli;

public enum TypeDocumentTheme {
    TECHNOLOGY_IT,MEDECINE_HEALTHCARE_ENTREPRENEURSHIP_BUSINESS,ENGINEERING_SCIENCES,ARTS_DESIGN_CREATIVITY,EDUCATION_SOCIELSCIENCES

}
