create table blacklisted_token_seq (next_val bigint) engine=InnoDB;
insert into blacklisted_token_seq values ( 1 );
create table blacklisted_token (id integer not null, created_at datetime(6), expiration_date datetime(6), expires_at datetime(6), user_id bigint not null, validated_at datetime(6), token varchar(255), primary key (id)) engine=InnoDB;
create table chat_message (read bit, chat_room_id bigint, id bigint not null auto_increment, receiver_id bigint, sender_id bigint, timestamp datetime(6), content TEXT, primary key (id)) engine=InnoDB;
create table chat_room (created_at datetime(6), id bigint not null auto_increment, lost_and_found_id bigint, user1_id bigint, user2_id bigint, primary key (id)) engine=InnoDB;
create table document (createdai date, document_access_level tinyint check (document_access_level between 0 and 1), document_theme tinyint check (document_theme between 0 and 4), document_visibility tinyint check (document_visibility between 0 and 1), id integer not null auto_increment, users_userid bigint, name varchar(255), document_type enum ('ARTICLE','CASE_STUDY','EBOOK','PHOTO','PRESENTATION','REPORT','RESEARCH_PAPER','THESIS','TUTORIAL','VIDEO'), primary key (id)) engine=InnoDB;
create table event (latitude float(53), longitude float(53), max_participants integer not null, end_time datetime(6), id bigint not null auto_increment, monitorungrecutement_id bigint, start_time datetime(6), description varchar(255), file_path varchar(255), location varchar(255), title varchar(255), typeevent enum ('CONCERT','CONFERENCE','SPORT'), typetheme enum ('BIG_DATA','BLOCKCHAIN','CLOUD_COMPUTING','COMPUTER_VISION','CYBERSECURITY','DATABASE','DEVOPS','EMBEDDED_SYSTEMS','GAME_DEVELOPMENT','IOT','MACHINE_LEARNING','MOBILE_DEVELOPMENT','NETWORKING','PROGRAMMING','QUANTUM_COMPUTING','SOFTWARE_ENGINEERING','UI_UX','WEB_DEVELOPMENT'), typeweather enum ('CLOUDY','RAINY','SUNNY'), primary key (id)) engine=InnoDB;
create table event_users (events_id bigint not null, users_userid bigint not null, primary key (events_id, users_userid)) engine=InnoDB;
create table feedback (assessment float(53) not null, date_of_submission datetime(6), events_id bigint, id_feedback bigint not null auto_increment, content varchar(255), suggestion varchar(255), feeling enum ('NEGATIVE','NEUTRAL','POSITIVE'), primary key (id_feedback)) engine=InnoDB;
create table interactive_publication (i_publication_id integer not null auto_increment, interaction_count integer not null, publication_moderation_status tinyint check (publication_moderation_status between 0 and 2), publication_status tinyint check (publication_status between 0 and 3), publication_visibility tinyint check (publication_visibility between 0 and 2), recommendation_score float(53) not null, publication_date datetime(6), scheduled_publish_time datetime(6), user_userid bigint, description varchar(255), title varchar(255), primary key (i_publication_id)) engine=InnoDB;
create table lost_and_found (created_at datetime(6), event_id bigint, id bigint not null auto_increment, user_id bigint, description varchar(255), image_url varchar(255), title varchar(255), type enum ('FOUND','LOST'), primary key (id)) engine=InnoDB;
create table mental_health (points integer not null, registration_status bit, stress_level integer not null, id_mental_health bigint not null auto_increment, last_wellness_session datetime(6), user_userid bigint, gamification_reward varchar(255), mindfulness_exercise_recommendation varchar(255), post_event_mental_state_report varchar(255), supportive_message varchar(255), emotional_state enum ('HAPPY','NEUTRAL','RELAXED','SAD','STRESSED'), primary key (id_mental_health)) engine=InnoDB;
create table monitoring_recruitment (quiz_id integer not null, result bit not null, created_at datetime(6), id bigint not null auto_increment, al_generated_report_link varchar(255), calendar_link varchar(255), description varchar(255), meeting_link varchar(255), quiz_results_link varchar(255), title varchar(255), status enum ('EEEE','RRRR'), primary key (id)) engine=InnoDB;
create table monitoring_recruitment_users (monitoringrecruitments_id bigint not null, users_userid bigint not null, primary key (monitoringrecruitments_id, users_userid)) engine=InnoDB;
create table notification (`read` bit, id bigint not null auto_increment, related_item_id bigint, timestamp datetime(6), user_id bigint, message varchar(255), title varchar(255), type varchar(255), primary key (id)) engine=InnoDB;
create table participation (id integer not null auto_increment, events_id bigint, registration_date datetime(6), qr_code_url varchar(255), participation_status enum ('ATTENDING','NOT_ATTENDING','WAITLISTED'), primary key (id)) engine=InnoDB;
create table payment (amount integer not null, participation_id integer, payment_date date, payment_status tinyint check (payment_status between 0 and 2), paymentid integer not null auto_increment, payment_method enum ('CREDIT_CARD','PAYPAL','STRIPE'), primary key (paymentid)) engine=InnoDB;
create table resource (id_resource integer not null auto_increment, resource_reservation_id integer, events_id bigint, name varchar(255), type_resource enum ('CHAIR','LAPTOP','MICROPHONE','PROJECTOR','ROOM','WHITEBOARD'), type_resource_status enum ('AVAILABLE','BROKEN','RESERVED','UNDER_MAINTENANCE'), primary key (id_resource)) engine=InnoDB;
create table resource_reservation (end_time date, reservation_id integer not null auto_increment, start_time date, created_at datetime(6), user varchar(255), primary key (reservation_id)) engine=InnoDB;
create table session (sessionid integer not null auto_increment, end_time datetime(6), events_id bigint, start_time datetime(6), location varchar(255), title varchar(255), session_status enum ('CANCELED','FINISHED','ONGOING','SCHEDULED'), primary key (sessionid)) engine=InnoDB;
create table smart_meeting (archived bit not null, audio_to_text_enabled bit not null, match_score float(53) not null, smartmeetingid integer not null auto_increment, follow_up_date datetime(6), transcription_date datetime(6), action_items varchar(255), keywords_extracted varchar(255), meeting_link varchar(255), search_keywords varchar(255), summary varchar(255), transcription_status varchar(255), transcription_text varchar(255), video_conference_tool varchar(255), primary key (smartmeetingid)) engine=InnoDB;
create table smart_meeting_participations (participations_id integer not null, smartmeetings_smartmeetingid integer not null, primary key (participations_id, smartmeetings_smartmeetingid)) engine=InnoDB;
create table sponsor (statut bit, id_sponsor bigint not null auto_increment, description varchar(255), image varchar(255), nom varchar(255), site_web varchar(255), niveau enum ('ARGENT','BRONZE','OR','PLATINE'), primary key (id_sponsor)) engine=InnoDB;
create table tags (tagid integer not null auto_increment, name varchar(255), primary key (tagid)) engine=InnoDB;
create table tags_sessions (sessions_sessionid integer not null, tags_tagid integer not null, primary key (sessions_sessionid, tags_tagid)) engine=InnoDB;
create table users (enabled bit not null, userid bigint not null auto_increment, address varchar(255), email varchar(255), password varchar(255), phone_number varchar(255), username varchar(255), primary key (userid)) engine=InnoDB;
create table users_interests (users_userid bigint not null, interests enum ('BIG_DATA','BLOCKCHAIN','CLOUD_COMPUTING','COMPUTER_VISION','CYBERSECURITY','DATABASE','DEVOPS','EMBEDDED_SYSTEMS','GAME_DEVELOPMENT','IOT','MACHINE_LEARNING','MOBILE_DEVELOPMENT','NETWORKING','PROGRAMMING','QUANTUM_COMPUTING','SOFTWARE_ENGINEERING','UI_UX','WEB_DEVELOPMENT')) engine=InnoDB;
create table users_user_role (users_userid bigint not null, user_role enum ('ADMIN','COMPANY','PARTICIPANT','SPEAKER','SPONSOR','TRAINER','USER')) engine=InnoDB;
alter table blacklisted_token add constraint UKd8f94e6nes93c15hn3lmijlld unique (token);
alter table event add constraint UKe9usd0bm1w6hvj45ai20cjwg9 unique (monitorungrecutement_id);
alter table blacklisted_token add constraint FK13bsx5i5p9vqmohh2jgljbi3w foreign key (user_id) references users (userid) on delete cascade;
alter table chat_message add constraint FKj52yap2xrm9u0721dct0tjor9 foreign key (chat_room_id) references chat_room (id);
alter table chat_message add constraint FK46s59psfyf53qh0ayebjnn6tu foreign key (receiver_id) references users (userid);
alter table chat_message add constraint FK5f82aoyy0jiwpj08qapfrxbh6 foreign key (sender_id) references users (userid);
alter table chat_room add constraint FK1q8fh3gov10ng51pvjsi4b80n foreign key (lost_and_found_id) references lost_and_found (id);
alter table chat_room add constraint FK3a0wdilod4wa2mt2ca9ef96d4 foreign key (user1_id) references users (userid);
alter table chat_room add constraint FKbr1wi7fg55r6opj5twlug294f foreign key (user2_id) references users (userid);
alter table document add constraint FK54jrif0st0fq501p7tbk4w2du foreign key (users_userid) references users (userid);
alter table event add constraint FKgetac3gj0s3p6ro1qard73jto foreign key (monitorungrecutement_id) references monitoring_recruitment (id);
alter table event_users add constraint FKtkqyn4u9402yehgs61u01mgwb foreign key (users_userid) references users (userid);
alter table event_users add constraint FKi8nipeapa6h0gwc89xiekjcy1 foreign key (events_id) references event (id);
alter table feedback add constraint FKsy14lof7qgrbpgbw67jdmc16q foreign key (events_id) references event (id);
alter table interactive_publication add constraint FK45psubkaixp81f1s03sxj32o9 foreign key (user_userid) references users (userid);
alter table lost_and_found add constraint FKj9qu6f9mtahqiuad6yjrt3fgq foreign key (user_id) references users (userid);
alter table lost_and_found add constraint FK7squ14vvgt54dj34dvqfn9rvi foreign key (event_id) references event (id);
alter table mental_health add constraint FKh0rdinkdmx46rxkjhjsgyqh9 foreign key (user_userid) references users (userid);
alter table monitoring_recruitment_users add constraint FKkfongn9815fs25h21weyo5gsf foreign key (users_userid) references users (userid);
alter table monitoring_recruitment_users add constraint FK1kdbk62ma9xdexq9a081oddgb foreign key (monitoringrecruitments_id) references monitoring_recruitment (id);
alter table notification add constraint FKnk4ftb5am9ubmkv1661h15ds9 foreign key (user_id) references users (userid);
alter table participation add constraint FKljue1vxwtimi66ajdc6516dcq foreign key (events_id) references event (id);
alter table payment add constraint FK7hvbohri2s3los32w9a3pypeh foreign key (participation_id) references participation (id);
alter table resource add constraint FKk74lbyjl1hijlq6m2a68n26qp foreign key (events_id) references event (id);
alter table resource add constraint FKinif26di8o425497k13o3ura9 foreign key (resource_reservation_id) references resource_reservation (reservation_id);
alter table session add constraint FKbgl1pa17i02c5okeu3twums85 foreign key (events_id) references event (id);
alter table smart_meeting_participations add constraint FKcxeux6rym9edox3h4dlfjys9y foreign key (participations_id) references participation (id);
alter table smart_meeting_participations add constraint FK8gyi4t5ywevfsdwx3bvjavy39 foreign key (smartmeetings_smartmeetingid) references smart_meeting (smartmeetingid);
alter table tags_sessions add constraint FKtdlykdmgx07emup2bxk40wwof foreign key (sessions_sessionid) references session (sessionid);
alter table tags_sessions add constraint FKfdklxbw9trb5dlwtjxjidhvp3 foreign key (tags_tagid) references tags (tagid);
alter table users_interests add constraint FKo7b49bg4mmjftboxer8neoeb4 foreign key (users_userid) references users (userid);
alter table users_user_role add constraint FK8rm4rlql1ytj25yp2ryqkoakf foreign key (users_userid) references users (userid);
