spring.application.name=nomPrenomClasseExamen
server.port=8082
### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/SmartMeet_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=wajdiwajdi1996
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#Logging
logging.level.root = info
logging.pattern.console= %d{yyyy-MM-dd HH:mm:ss} -%level -%logger{60} %msg %n

spring.security.user.name=user
spring.security.user.password=user
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sps2022noreply@gmail.com
spring.mail.password=bhfqrtfpfkrimolg
spring.mail.properties.mail.smtp.starttls.required=true
application.mailing.frontend.activation-url=http://localhost:4200/activate
application.mailing.frontend.reset-password-url=http://localhost:4200/reset-password

# application.properties
# Cle secrete utilisee pour signer et verifier les JWT
Smartmeet.app.jwtSecret=jKU54A1RxGXdvzN8Xql08JrN8vKAcIqVIsb4LiZPK0M=

# Duree dexpiration du JWT en millisecondes (exemple: 1 heure = 3600000 ms)
Smartmeet.app.jwtExpirationMs=3600000

# R�pertoire o� les fichiers seront sauvegard�s (adapte le chemin � ton projet)
app.upload.dir=./uploads


# Taille maximale d'un fichier upload� (ex: 5 Mo)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Active les logs des requ�tes HTTP
logging.level.org.springframework.web=DEBUG
logging.level.tn.esprit.examen=DEBUG


# Python API Configuration
python.api.url=http://localhost:5000
python.api.timeout=5000

logging.level.org.springframework.web.cors=DEBUG
logging.level.org.springframework.security=DEBUG
